---

- hosts: "{{ hosts_group | default('all') }}"

  vars_files:
    - 'example-vars.yml'

  roles:
    - { role: ansible-nodejs, tags: ['ansible-nodejs'] }
    - { role: "{{ role_name | default('ansible-pm2') }}", tags: ['ansible-pm2'] }
